# Generated by Django 4.2.15 on 2025-01-12 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_order_product_order_content_type_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order2D',
        ),
    ]
